# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
