# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0002_auto_20181113_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volumes.Cluster')),
                ('protocols', models.ManyToManyField(to='volumes.Protocol')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('size', models.IntegerField()),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volumes.Protocol')),
                ('svm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volumes.SVM')),
            ],
        ),
    ]
