# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0003_protocol_svm_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svm',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volumes.Cluster'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volumes.Protocol'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='svm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volumes.SVM'),
        ),
    ]
